Removed existential deposit
stabilityprotocol/stability pull request #11
Opened 2023-01-27 00:21 UTC by clostao

## Description

Frontier has a field called `ExistentialDeposit` in `pallet_balances::Config` that would behave as a unique OnCreation fee. I've updated this field to zero.

## Motivation

Balance of new accounts would be reducted their balance by `ExistentialDeposit`, this is not a desired behaviour.

## Impact on the project

`runtime/lib.rs`

2023-01-27 15:01 UTC, GabrielMartinezRodriguez approved these changes

2023-01-27 22:06 UTC, deblanco requested changes

2023-01-27 22:06 UTC, deblanco commented on runtime/src/lib.rs
> +    pub const ExistentialDeposit: u128 = 0;
Because this is a spec of our chain, could you move the value to our cfg file?

2023-01-28 10:22 UTC, clostao commented on runtime/src/lib.rs
> +    pub const ExistentialDeposit: u128 = 0;
done

2023-01-29 17:29 UTC, deblanco requested changes
https://github.com/stabilityprotocol/stability/blob/main/docs/PARAMETERS.md

Could you add info about this change in the PARAMETERS doc?

2023-01-30 10:17 UTC, deblanco approved these changes
LGTM!

2023-01-30 10:36 UTC, merged