Update blockchain
stabilityprotocol/stability pull request #131
Opened 2023-10-19 09:18 UTC by GabrielMartinezRodriguez

## Description

## Types of changes

What types of changes does your code introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-11-07 13:38 UTC, clostao approved these changes
Looks good to me

2023-11-11 22:24 UTC, deblanco requested changes

2023-11-11 22:24 UTC, deblanco commented on primitives/runner/src/lib.rs
>  			target: "evm",
We need to take this back: token, validator etc

2023-11-11 22:24 UTC, deblanco commented on primitives/runner/src/lib.rs
> +		let actual_base_fee = effective_gas.saturating_mul(base_fee);
unused remove

2023-11-14 16:34 UTC, deblanco approved these changes

2023-11-15 11:23 UTC, deblanco submitted a review, later dismissed

2023-11-15 11:41 UTC, deblanco approved these changes

2023-11-15 11:41 UTC, clostao approved these changes
LGTM!

2023-11-15 11:54 UTC, merged