[DRAFT] Validator set
stabilityprotocol/stability pull request #26
Opened 2023-02-05 15:57 UTC by GabrielMartinezRodriguez

## Description

Add a pallet for manage the validators after the genesis

## Types of changes

What types of changes does your code introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-02-16 08:49 UTC, clostao submitted a review, later dismissed
LGTM

2023-02-16 10:26 UTC, deblanco requested changes

2023-02-16 10:33 UTC, GabrielMartinezRodriguez commented on Cargo.toml
> +	'pallets/root-controller',
solve

2023-02-16 10:33 UTC, GabrielMartinezRodriguez commented on precompiles/validator-controller/Cargo.toml
> +	"precompile-utils/std",
solve

2023-02-17 11:42 UTC, clostao approved these changes
LGTM! Good job Gabriel!

2023-02-19 17:59 UTC, merged