Fix mismatch between `BlockGasLimit` and maximum transaction gas limit
stabilityprotocol/stability pull request #30
Opened 2023-02-08 15:47 UTC by clostao

## Description

In every native EVM chain block gas limit is the maximum gas limit that a transaction can have. Due to Substrate's operations this is not the actual case for Frontier-based blockchains. 

`BlockWeights` and `BlockGasLimit` parameter types in `runtime/lib.rs` have been updated in order to force this to be true.

Additionally, the way we get `BlockWeights` value has changed in order to enforce the condition above. Instead of deriving it from `MAXIMUM_BLOCK_WEIGHT` (that describes how much weight can be processed in one block) it is derived from a `TARGET_BLOCK_GAS_LIMIT`. After the corresponding calculation is done, it is checked that the result does not overpass the maximum, throwing an error in that case.

## Types of changes

What types of changes does your code introduce?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-02-08 16:30 UTC, deblanco requested changes

2023-02-08 16:30 UTC, deblanco commented on docs/PARAMETERS.md
> +### Block size limitting
limiting*

2023-02-08 16:30 UTC, deblanco commented on docs/PARAMETERS.md
> +One important feature of every blockchain is to know how the blocks are being formed and limitting their size in order to assure security and latency. Substrate itself already implements this through
limiting*

2023-02-08 16:30 UTC, deblanco commented
LGTM!

2023-02-08 21:51 UTC, deblanco approved these changes

2023-02-09 09:17 UTC, GabrielMartinezRodriguez approved these changes

2023-02-09 10:41 UTC, merged