Add support for paying fees in non-native tokens
stabilityprotocol/stability pull request #36
Opened 2023-02-16 16:13 UTC by clostao

## Description

Add support for paying fees in non-native tokens

## Types of changes

What types of changes does your code introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-03-09 15:31 UTC, clostao commented on precompiles/map-svm-evm-controller/src/lib.rs
> +		let substrate_account =
Wouldn't be better two have `linkOf(address)` returning `ADDRESS_ZERO` when there is no linked substrate linked account?

2023-03-09 15:31 UTC, clostao commented on pallets/map-svm-evm/src/lib.rs
> +			let who = ensure_signed(origin)?;
Check that evm address is not `ADDRESS_ZERO`

2023-03-09 15:31 UTC, clostao commented on precompiles/map-svm-evm-controller/src/tests.rs
> +			.execute_reverts(|output| output == b"EVM account not linked")
Change to expected `ZERO_ADDRESS`

2023-03-10 09:57 UTC, GabrielMartinezRodriguez requested changes

2023-03-10 09:57 UTC, GabrielMartinezRodriguez commented on pallets/erc20-manager/src/lib.rs
> +					Error::<T>::InsufficientBalance
I would change the name of the error. For instance: OverflowBalance

2023-03-10 09:57 UTC, GabrielMartinezRodriguez commented on pallets/evm-fee-controller/src/lib.rs
> +			frame_support::log::info!("refunded fees: {:?}", excess_fee_token_amount);
This will saturate the console. I would remove this logs, or change it to debug level.

2023-03-10 09:57 UTC, GabrielMartinezRodriguez commented on pallets/token-fee-controller/validator-fee-selector/src/lib.rs
> +			ValidatorSupportFeeToken::<T>::get(validator, token)
Here we would have to check if the token is supported too, like in the `validator_supported_tokens` function

2023-03-10 10:14 UTC, GabrielMartinezRodriguez commented on pallets/map-svm-evm/src/lib.rs
> +			if let Some(_) = evm_linked_account {
I created a new macro for this case.`none_or_error`

2023-03-10 10:49 UTC, clostao commented on pallets/evm-fee-controller/src/lib.rs
> +			frame_support::log::info!("refunded fees: {:?}", excess_fee_token_amount);
yup, I missed to delete it. Good catch =)

2023-03-10 10:55 UTC, clostao commented on pallets/erc20-manager/src/lib.rs
> +					Error::<T>::InsufficientBalance
I created two errors `OverflowBalance` and `UnderflowBalance` corresponding to `withdraw_amount` and `deposit_amount`.

2023-03-10 11:06 UTC, clostao commented on pallets/erc20-manager/src/lib.rs
> +					Error::<T>::InsufficientBalance
Check out this commit be0fefd6606fd6ce56837b98967304f82050681b

2023-03-10 11:07 UTC, GabrielMartinezRodriguez commented on precompiles/map-svm-evm-controller/src/lib.rs
> +		let substrate_account =
Changed 👍

2023-03-10 11:07 UTC, GabrielMartinezRodriguez commented on precompiles/map-svm-evm-controller/src/tests.rs
> +			.execute_reverts(|output| output == b"EVM account not linked")
Changed

2023-03-10 11:34 UTC, GabrielMartinezRodriguez commented on pallets/map-svm-evm/src/lib.rs
> +			let who = ensure_signed(origin)?;
Changed

2023-03-13 14:01 UTC, deblanco commented on docker/test/Dockerfile
> +COPY test-utils ./test-utils
duplicated!

2023-03-13 18:28 UTC, deblanco approved these changes
LGTM!
Very good, this settles the base of a new trip! congrats

2023-03-13 19:05 UTC, merged