Business Share Revenue
stabilityprotocol/stability pull request #55
Opened 2023-03-23 12:29 UTC by clostao

## Description

A fee system where dApps will receive a share of the gas used in their contracts. 

## Types of changes

What types of changes does your code introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-03-29 15:18 UTC, deblanco requested changes
Missing docs.

2023-03-30 09:57 UTC, GabrielMartinezRodriguez commented
> Missing docs.

2023-03-30 09:58 UTC, GabrielMartinezRodriguez commented
> Missing docs.

done

2023-03-30 13:04 UTC, GabrielMartinezRodriguez commented on primitives/runner/src/lib.rs
> +				H160::zero(),
Maybe is good idea use the `FeeRewardsVaultController` as from instead of `0`

2023-03-30 15:26 UTC, clostao commented on primitives/runner/src/lib.rs
> +				H160::zero(),
Already fixed

2023-03-30 15:27 UTC, clostao commented on runtime/src/lib.rs
> +			// IMPORTANT: TO REMOVE BEFORE MERGING
true

2023-03-30 15:46 UTC, clostao commented on runtime/src/lib.rs
> +			// IMPORTANT: TO REMOVE BEFORE MERGING
As we discussed, we're merging it and replacing it when custom pallet_balances is implemented

2023-03-31 10:09 UTC, deblanco requested changes

2023-03-31 13:09 UTC, deblanco approved these changes

2023-03-31 14:51 UTC, GabrielMartinezRodriguez approved these changes

2023-03-31 14:51 UTC, merged