feat: conversion rate calculated in contract selected by validator
stabilityprotocol/stability pull request #83
Opened 2023-05-04 15:03 UTC by clostao

## Description

Formerly, conversion rate was managed centralized in `ValidatorFeeManagerPrecompile` now in this precompiled contract manages a map value between `validators => conversion_rate_manager` where the `conversion_rate_controller` is the contract designed by the validator. There is a default conversion rate manager that would manage validators conversion rate if no other controller is specified. 

This would be the default conversion rate manager:

```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.3;

contract ConversionRateManager {
    address public owner = 0xaf537bd156c7E548D0BF2CD43168dABF7aF2feb5;

    struct ConversionRate {
        uint256 numerator;
        uint256 denominator;
    }

    mapping(address => ConversionRate) public tokenConversionRate;

    function getConversionRate(address /*sender*/, address/*validator*/, address token) external view returns(uint256, uint256) {
        ConversionRate memory cr = tokenConversionRate[token];

        bool isDefaultConversionRate = cr.denominator == 0;

        return isDefaultConversionRate ? (1, 1) : (cr.numerator, cr.denominator);
    }

    function setTokenConversionRate(address token, uint256 numerator, uint256 denominator) public {
        require(msg.sender == owner, "ConversionRateManager: ONLY_OWNER");

        tokenConversionRate[token] = ConversionRate(numerator, denominator);
    }

}
```

## Types of changes

What types of changes does your code introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-05-08 20:42 UTC, deblanco requested changes
Could you update the precompile gas cost according to #84?

2023-05-08 20:42 UTC, deblanco commented on precompiles/token-fee-controller/validator-fee-selector/src/lib.rs
>  /// Solidity selector of the Transfer log, which is the Keccak of the Log signature.
wtf

2023-05-11 09:52 UTC, GabrielMartinezRodriguez approved these changes
LGTM

2023-05-11 09:53 UTC, deblanco approved these changes

2023-05-11 10:01 UTC, merged